### ISSUE TITLE
Add ability to create many certificates

### ISSUE THREAD

**Issue by KoryIII** [tomdess/docker-haproxy-certbot#15]
Hello!
Please, maybe you will add the ability to create separate certificates?
This is necessary so that users do not see other domains located at the same IP address.
Thank you!

**Comment by jaskipper** [comment]
I've been wanting this as well. I've managed to make it work by changing the `certs.sh` file to the following code (see below). @tomdess , do you see any issues with this, and would there be any issues with renewals?

```
#!/usr/bin/env bash

if [ -n "$CERT1" ]; then
    if [ "$STAGING" = true ]; then
        for certname in ${!CERT*}; do
            certbot certonly --no-self-upgrade -n --text --standalone \
            --preferred-challenges http-01 \
            --staging \
            -d "${!certname}" --keep --expand --agree-tos --email "$EMAIL" \
            || exit 2
        done
    else
        for certname in ${!CERT*}; do
          	certbot certonly --no-self-upgrade -n --text --standalone \
            --preferred-challenges http-01 \
            -d "${!certname}" --keep --expand --agree-tos --email "$EMAIL" \
            || exit 1
        done
    fi

    mkdir -p /etc/haproxy/certs
    for site in `ls -1 /etc/letsencrypt/live | grep -v ^README$`; do
        cat /etc/letsencrypt/live/$site/privkey.pem \
          /etc/letsencrypt/live/$site/fullchain.pem \
          | tee /etc/haproxy/certs/haproxy-"$site".pem >/dev/null
    done
fi

exit 0
```
I also changed my docker-compose.yml file, removing the CERTS environment variable, and adding multiple CERT1, CERT2 environment variables. See example below.

```
version: '3'
services:
    haproxy:
        container_name: lb-haproxy-certbot
        environment:
            - EMAIL=yourname@yoursite.com
            - STAGING=false
            - CERT1=yoursite.com, www.yoursite.com
            - CERT2=yoursite2.com, www.yoursite2.com
        volumes:
            - './data/letsencrypt:/etc/letsencrypt'
            - './data/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg'
            - './certs.sh:/certs.sh'
        ports:
            - '80:80'
            - '443:443'
        image: 'ghcr.io/tomdess/docker-haproxy-certbot:master'
        restart: always
```
